"""empty message

Revision ID: 423f3ade81a9
Revises: 
Create Date: 2021-07-08 16:45:29.923602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423f3ade81a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('des', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'des')
    # ### end Alembic commands ###
